freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg install -y rubygem-jekyll
    - pkg install -y rubygem-jekyll-sitemap
    - pkg install -y npm
    - npm install -g @commonshost/cli
  build_script: jekyll build
  login_script: commonshost login --username asozialesnetzwerk --password 367648314184826880
  deploy_script: commonhost deploy --domain asozialesnetzwerk.commons.host --root ./_site
